### ISSUE TITLE
Opera and IE

### ISSUE THREAD

**Issue by Born2Rock** [HTML50/cubeTransition.js#1]
Hi! Wired script just in time for me, but there is a big problem.
It does not work in Opera and IE.

Is it bossible to solve it. I used this in my project and have a deadline in 3 days.

Many thanks.

**Comment by HTML50** [comment]
@Born2Rock
well, all my projects are based on `chrome`.
I will try my best to make it work for Opera and IE.

by the way, what's the version of your IE and Opera?

**Comment by Born2Rock** [comment]
@HTML50 Many thanks! It seems that the same way of animation doesn't work at all in OPERA and IE. Look at the site i've been inspered before found your code http://rdcm.com/

**Comment by HTML50** [comment]
@Born2Rock 
hi, i have modified it.
and I tested on IE11 and Opera 41, works now.
i think this kind of effect works fine on IE10+, if you want to use a lower version of IE, maybe hard to make it.
anyway, you can do your project in many ways.
check the code, talk later.

**Comment by Born2Rock** [comment]
@HTML50 Many thanks!
But where can i check it? I do not see the commit.

**Comment by HTML50** [comment]
@Born2Rock i forget to upload it to the master repo.
check it now
